In [2]:
import torch

In [3]:
# the first dimension is the column index and the second dimension is the row index.
a = torch.randn(3,2)
print(a)

# so, column 1, row two would be accessed as:
print(a[0][1])

# Also, torch.shape makes sense in this context
print(a.shape)

tensor([[ 0.9487,  1.7910],
        [-0.0124, -1.2426],
        [-0.7375,  0.6749]])
tensor(1.7910)
torch.Size([3, 2])


In [4]:
# However, initializing from arrays is a little unintuitive:

b = torch.tensor(
    (
        [1,3,5],
        [2,4,6]
    )
)
print(b)

# things are declared row by row. This makes it so if we draw out the vector, it looks the same as printed.

tensor([[1, 3, 5],
        [2, 4, 6]])


In [13]:
# element-wise multiplying:
c = torch.tensor(
    (
        [1,3,5],
        [1,3,5]
    )
)

w1 = torch.tensor(
    (
        [2],
        [4]
    )
)

print(c.shape)
print(w1.shape)

print(c * w1)

torch.Size([2, 3])
torch.Size([2, 1])
tensor([[ 2,  6, 10],
        [ 4, 12, 20]])


# How does it work in 3D

In [2]:
import torch
w1 = torch.randn(4,2,3) # 4 matrices(z), 2 rows (y), 3 columns (x). Read from right to left.

w2 = torch.randn(4,3,2) # 4 matrices, 3 rows, 2 columns. Read from right to left.

w1 @ w2

tensor([[[ 0.6394, -2.1678],
         [-1.3305, -0.1361]],

        [[-0.7471, -1.1691],
         [ 2.2040,  1.5449]],

        [[-0.8300, -0.8842],
         [-1.4494, -2.7023]],

        [[ 1.5276,  0.5075],
         [ 0.3999,  0.3499]]])

In [26]:
a = torch.tensor([1,2,3,4,5])
print(a)
# start:stop:step
# print(a[:3])
# print(a[3:])
# print(a[1:4])
# print(a[1::2])

print(a[::])

b = torch.tensor(
    (
        [1,2,3],
        [4,5,6],
        [7,8,9]
    )
)



tensor([1, 2, 3, 4, 5])
tensor([1, 2, 3, 4, 5])


In [34]:
a = torch.randn(4,8,10)

# 4 examples of 8 characters, each with a 10d embedding.

# where each is a 10d
1,2,3,4,5,6,7,8
1,2,3,4,5,6,7,8
1,2,3,4,5,6,7,8
1,2,3,4,5,6,7,8

# (1,2), (3,4), (5,6), (7,8)
# ...

# 4 x 4 x 20

# view flattens the tensor, then wraps it in a new shape.

# example: (0-9 1d)
a = torch.tensor([1,2,3,4,5,6,7,8,9])
print(a.view(3,3))

a.view(1, 9)

# how does it behave with multiple dimensions?
b = torch.tensor([1,2,3,4,5,6,7,8,9,10,11,12]) # 2x2x3
print(b.view(2,2,3))

# as you can see, it recursively fills in each dimension, starting from highest dim (far left)


a = torch.randn(4,8,10)
# now let's do our example from before
a.view(4,4,20)

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])
tensor([[[ 1,  2,  3],
         [ 4,  5,  6]],

        [[ 7,  8,  9],
         [10, 11, 12]]])


tensor([[[-1.5645e+00, -4.9830e-01,  8.8649e-01, -3.8448e-01,  3.2296e-01,
          -2.0987e-01,  4.0306e-01, -1.0967e-02, -1.7346e+00,  7.9179e-01,
          -1.2899e+00,  1.1946e-01,  9.6020e-01, -1.2138e+00, -1.1839e+00,
           7.1085e-01,  1.4945e+00, -2.1268e+00, -8.5681e-01,  1.2719e-01],
         [ 1.1747e+00,  3.1840e-01,  7.7772e-01,  1.1194e-01,  7.7812e-01,
           9.1624e-01, -1.8379e-01,  2.2753e-01, -7.5349e-01,  7.4623e-01,
          -4.3257e-01, -1.8963e-01, -1.5817e-01,  2.8762e+00,  3.9608e-01,
          -8.3580e-01, -4.8802e-01, -1.3250e-01,  7.6721e-01, -4.0194e-01],
         [ 7.0194e-03, -4.0573e-01, -3.2852e-01,  7.8484e-02, -1.0080e+00,
           9.9706e-01,  9.0699e-01,  1.0801e-02,  1.0435e+00,  8.0525e-01,
           5.8775e-01,  2.5340e-01, -1.8733e+00,  4.4745e-01,  1.0970e-01,
          -6.0851e-01,  5.7152e-01,  5.2615e-01, -2.0173e-01, -8.4560e-01],
         [ 1.9604e+00,  4.8493e-01, -1.7861e+00, -1.0471e+00, -3.6576e-01,
          -5.9660e-01,